### ISSUE TITLE
Searching send too much API request to backend

### ISSUE THREAD

**Issue by rosschiu** [bsol-oss/react-datatable#13]
Currently when we type and search using the component, all re-render event will trigger API call.

Current behavior:
![image](https://github.com/bsol-oss/react-datatable/assets/18388411/1845e53d-7c95-43c4-a065-7e52c71bfffc)
![image](https://github.com/bsol-oss/react-datatable/assets/18388411/93c09a43-e158-4474-9f53-961f62148999)
![image](https://github.com/bsol-oss/react-datatable/assets/18388411/1984cd1a-1b2b-403a-93d3-0b0d9a0c6659)

In fact the optimal way is to let user press Enter or click search button to trigger the search.
I suggest to compose input box with a search button on right, refer to how this should be done in Chakra UI:
https://chakra-ui.com/docs/components/input#add-elements-inside-input

```[tasklist]
### Tasks
- [ ] Add a search button for all search input box using the UI above.  The search icon should accept theme color same as primary color
- [ ] when API request is sent out, show a spinner to replace the search button and disable input.  When search is done re-enable input.  As a result, the design should be the table got a master "isLoading" state and pass on to all children.  components such as search field and button decide their own behavior in response to isLoading change.
- [ ] Also allow to press Enter to trigger search
```
